import { BodyFunction, BracketConfig, CodeGenerationConfig, CodeLike, Context, State } from "./Interface";
export declare class ContextImpl implements Context {
    config: CodeGenerationConfig;
    state: State;
    parent: Context;
    children: Context[];
    ifCondition: boolean;
    isIBracket: boolean;
    isIBracketFirst: boolean;
    currentBracketConfig: BracketConfig;
    codeFunctionCache: any[];
    constructor(segement: undefined | null | CodeLike, config: CodeGenerationConfig, state: State, parent: Context);
    if(condition: boolean, ...code: CodeLike[]): Context;
    elseIf(condition: boolean, ...code: CodeLike[]): Context;
    ifAll(condition: boolean[], ...code: CodeLike[]): Context;
    ifAny(condition: boolean[], ...code: CodeLike[]): Context;
    else(...code: CodeLike[]): Context;
    bracket(char: string, content: BodyFunction): Context;
    body(content: BodyFunction): Context;
    ibracket(char: string): Context;
    ibracketEnd(): Context;
    append(...text: CodeLike[]): Context;
    newLine(n?: number): Context;
    generate(): string;
    generateLines(): string[];
    private cache;
    private currentLine;
    private _add;
    private _processSegement;
    private _processCodeFunction;
    private _addStringSegement;
    private _finishCurrentLine;
}
